[platformio]
default_envs = my-esp32s3-st7735

[env:my-esp32s3-st7735]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

build_flags =
	-DST7735_DRIVER=1
	-DST7735_REDTAB=1
	-DTFT_WIDTH=128
	-DTFT_HEIGHT=160
	-DTFT_CS=10
	-DTFT_DC=9
	-DTFT_RST=8
	-DTFT_SCLK=12
	-DTFT_MOSI=11
	-DTFT_BL=-1
	-DROTATION=1
	-DSMOOTH_FONT=1
	-DHAS_SDCARD=0
	-DDISABLE_GPS=1
	-DDISABLE_RFID=1
	-DDISABLE_IR=1
	-DDISABLE_RF=1
	-DDISABLE_FM=1
	-DDISABLE_BLUETOOTH=1
	-DDISABLE_BADUSB=1
	-DDISABLE_JS=1
	-DDISABLE_NRF24=1
	-DDISABLE_CC1101=1
	-DDISABLE_PN532=1
	-DDISABLE_MFRC522=1
	-DBRUCE_VERSION='"dev"'
	-DEEPROMSIZE=128
	-DLH=8
	-DLW=6
	-w
	-Wl,--print-memory-usage
	-Wl,--gc-sections
	-DGIT_COMMIT_HASH='"Homebrew"'
	-DSAFE_STACK_BUFFER_SIZE=4096
	-DCORE_DEBUG_LEVEL=1

lib_deps =
	bblanchon/ArduinoJson @ ^7.0.0
	NTPClient
	Timezone
	ESP32Time
	h2zero/NimBLE-Arduino@^1.4.0
	nrf24/RF24 @ ^1.4.9
	Bodmer/JPEGDecoder
	paulstoffregen/OneWire@^2.3.8
	tobozo/ESP32-PSRamFS
	bitbank2/AnimatedGIF
	WireGuard-ESP32
	IRremoteESP8266
	Time
